import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Efstathios Stivaros | Ruby on Rails Developer from London',
  description: 'Generated by create next appEfstathios Stivaros, a Ruby on Rails developer based in London. Explore my projects and expertise in web application development.',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
